import { expect, test } from '@playwright/test'
import type { OperationsSnapshot } from '../src/api'

const headers = { Authorization: 'Bearer browser-operator-token' }
const path = '/api/v1/operations/handling/batch'

test('bulk handling reviews its scope, records each action, survives reload and clears selection on filter change', async ({ page, request }, info) => {
  await expect.poll(async () => (await (await request.get('/api/v1/operations', { headers })).json()).problems.length).toBe(2)
  await page.goto('/?token=browser-operator-token')
  const batch = page.getByRole('region', { name: '批量问题处置' })
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await expect(batch).toContainText('已选择 2 / 50 项')
  await expect(batch.locator('li')).toHaveCount(2)
  await expect(batch).toContainText('browser_ram_notice')
  await expect(batch).toContainText('browser_ram_secondary')
  await batch.getByLabel('批量操作', { exact: true }).selectOption('assign')
  await expect(batch.getByRole('button', { name: '对选中 2 项执行' })).toBeDisabled()
  await batch.getByLabel('批量责任人').selectOption('browser-oncall')
  await batch.getByLabel('批量处理备注').fill('统一交接给值班人员。')
  await expect(batch).toContainText('指派给 browser-oncall')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await batch.screenshot({ path: info.outputPath('batch-review.png') })
  await batch.getByRole('button', { name: '对选中 2 项执行' }).click()
  await expect(batch).toContainText('已对 2 个问题完成指派责任人')
  let snapshot: OperationsSnapshot = await (await request.get('/api/v1/operations', { headers })).json()
  for (const p of snapshot.problems) {
    expect(p.handling.assignee).toBe('browser-oncall')
    expect(p.handling.history.at(-1)?.actor).toBe('browser-oncall')
    expect(p.handling.history.at(-1)?.note).toBe('统一交接给值班人员。')
  }
  await page.reload()
  await expect(page.locator('.problem .owner').filter({ hasText: 'browser-oncall' })).toHaveCount(2)
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await batch.getByLabel('批量操作', { exact: true }).selectOption('progress')
  await batch.getByLabel('批量处理进度').selectOption('watching')
  await batch.getByRole('button', { name: '对选中 2 项执行' }).click()
  await expect(batch).toContainText('已对 2 个问题完成更新进度')
  snapshot = await (await request.get('/api/v1/operations', { headers })).json()
  expect(snapshot.problems.every(p => p.handling.status === 'watching')).toBe(true)
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await page.getByLabel('搜索主机或问题').fill('browser_ram_secondary')
  await expect(batch).toContainText('已选择 0 / 50 项')
  await expect(batch).toContainText('筛选条件已改变')
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await expect(batch.locator('li')).toHaveCount(1)
  await expect(batch.locator('li')).not.toContainText('browser_ram_notice')
})

test('one conflicting item rejects the entire batch and refresh never advances selected revisions', async ({ page, request }) => {
  await page.goto('/?token=browser-operator-token')
  const batch = page.getByRole('region', { name: '批量问题处置' })
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await batch.getByLabel('批量操作', { exact: true }).selectOption('comment')
  await batch.getByLabel('批量处理备注').fill('保留批量备注草稿')
  const before: OperationsSnapshot = await (await request.get('/api/v1/operations', { headers })).json()
  const changed = before.problems[0]!
  expect((await request.post('/api/v1/operations/handling', { headers, data: {
    id: changed.id, revision: changed.handling.revision, action: 'comment', note: '另一个页面先处理了其中一项',
  } })).ok()).toBe(true)
  const afterExternal = await (await request.get('/api/v1/operations', { headers })).json()
  await batch.getByRole('button', { name: '对选中 2 项执行' }).click()
  await expect(batch.getByRole('alert')).toContainText('整批未提交')
  await expect(batch.getByLabel('批量处理备注')).toHaveValue('保留批量备注草稿')
  await expect(batch.getByRole('button', { name: '对选中 2 项执行' })).toBeDisabled()
  const after = await (await request.get('/api/v1/operations', { headers })).json()
  expect(after.problems.map((p: OperationsSnapshot['problems'][number]) => p.handling)).toEqual(afterExternal.problems.map((p: OperationsSnapshot['problems'][number]) => p.handling))
  await page.getByRole('button', { name: '刷新总览', exact: true }).click()
  await expect(batch.getByRole('button', { name: '对选中 2 项执行' })).toBeDisabled()
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await batch.getByRole('button', { name: '对选中 2 项执行' }).click()
  await expect(batch).toContainText('已对 2 个问题完成补充备注')
})

test('storage failure preserves selection and notes; a read-only user cannot invoke bulk handling', async ({ page, request }) => {
  await page.goto('/?token=browser-operator-token')
  const batch = page.getByRole('region', { name: '批量问题处置' })
  await batch.getByRole('button', { name: '选择当前显示（最多 50 项）' }).click()
  await batch.getByLabel('批量处理备注').fill('磁盘恢复后再提交')
  const before: OperationsSnapshot = await (await request.get('/api/v1/operations', { headers })).json()
  await page.route('**' + path, route => route.fulfill({ status: 503, body: 'storage failed' }))
  await batch.getByRole('button', { name: '对选中 2 项执行' }).click()
  await expect(batch.getByRole('alert')).toContainText('整批未提交')
  await expect(batch).toContainText('已选择 2 / 50 项')
  await expect(batch.getByLabel('批量处理备注')).toHaveValue('磁盘恢复后再提交')
  await page.unroute('**' + path)
  const after: OperationsSnapshot = await (await request.get('/api/v1/operations', { headers })).json()
  expect(after.problems.map(p => p.handling)).toEqual(before.problems.map(p => p.handling))
  await batch.getByRole('button', { name: '对选中 2 项执行' }).click()
  await expect(batch).toContainText('已对 2 个问题完成确认问题')
  await page.goto('/?token=browser-viewer-token')
  await expect(page.getByRole('heading', { name: '问题中心', exact: false })).toBeVisible()
  await expect(page.getByRole('region', { name: '批量问题处置' })).toHaveCount(0)
  await expect(page.getByRole('checkbox', { name: /^选择问题 / })).toHaveCount(0)
  expect((await request.post(path, { headers: { Authorization: 'Bearer browser-viewer-token' }, data: {} })).status()).toBe(403)
})
