import { test, expect } from '@playwright/test'
import { metricHelp, dimensionHelp, unitHelp } from '../src/metricHelp'
import type { Chart } from '../src/api'
const chart = (context: string): Chart => ({ id: context, context, title: 'Original title', units: 'percentage', chart_type: 'stacked', priority: 1, update_every: 1, plugin: 'test', module: 'test', family: 'test', labels: null, dimensions: [], first_entry: 0, last_entry: 0 })

test('Chinese explanations preserve contexts, units and unknown metric boundaries', () => {
  expect(metricHelp(chart('system.cpu'))).toContain('CPU 时间')
  expect(metricHelp({ ...chart('system.cpu'), context: '', id: 'system.load' })).toContain('不是 CPU 使用率')
  expect(metricHelp({ ...chart('system.cpu'), context: 'other.metric' })).not.toContain('CPU 时间在')
  expect(metricHelp(chart('httpcheck.cert_expiry.instance'))).toContain('证书')
  expect(metricHelp(chart('couchbase.bucket_ops_per_sec'))).toContain('CouchDB / Couchbase')
  expect(metricHelp(chart('external.custom'))).toContain('尚无专用释义')
  expect(unitHelp('MiB')).toContain('1024 KiB')
  expect(unitHelp('requests/s')).toContain('每秒请求数')
  expect(unitHelp('value')).toContain('核对采集配置')
  const cpu = dimensionHelp(chart('system.cpu'), { id: 'idle', name: 'idle', algorithm: 'absolute' })
  expect(cpu).toContain('CPU 空闲时间占比')
  expect(cpu).toContain('不是累计高度')
  expect(dimensionHelp(chart('custom.metric'), { id: '<script>', name: '<script>', algorithm: 'absolute' })).toContain('不直接代表健康状态')
})

test('all-metrics, preset and personal dashboards expose Chinese hover help and touch details', async ({ page }, info) => {
  await page.goto('/?view=charts&token=browser-test-token')
  await page.getByPlaceholder('筛选图表…').fill('system.cpu')
  const card = page.locator('.card').filter({ has: page.locator('.id', { hasText: /^system.cpu$/ }) }).first()
  await expect(card.locator('.title')).toHaveAttribute('title', /CPU 时间在/)
  await card.locator('.title').hover()
  await expect(card.locator('.units')).toHaveAttribute('title', /百分比/)
  await card.scrollIntoViewIfNeeded()
  await expect(card.locator('.u-legend')).toBeVisible()
  const system = card.locator('.u-series').filter({ has: page.locator('.u-label', { hasText: /^system$/ }) })
  await expect(system).toHaveAttribute('title', /内核执行时间占比/)
  await expect(system.locator('.u-value')).toHaveAttribute('title', /不是累计高度/)
  const user = card.locator('.u-series').filter({ has: page.locator('.u-label', { hasText: /^user$/ }) })
  await expect(user).toHaveAttribute('title', /用户程序执行时间占比/)
  await card.getByText('中文指标说明', { exact: true }).click()
  await expect(card.locator('.metric-help p')).toBeVisible()
  await expect(card.locator('.metric-help p')).toContainText('不等于 0')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('metric-help.png'), fullPage: true })
  await card.locator('summary').focus()
  await page.keyboard.press('Enter')
  await expect(card.locator('.metric-help p')).toBeHidden()
  await page.getByRole('button', { name: '常用聚合看板', exact: true }).click()
  await expect(card.locator('.title')).toHaveAttribute('title', /CPU 时间在/)
  await page.getByRole('button', { name: '复制为个人看板', exact: true }).click()
  await page.getByRole('button', { name: '保存看板', exact: true }).click()
  await card.scrollIntoViewIfNeeded()
  await expect(card.locator('.u-series').filter({ has: page.locator('.u-label', { hasText: /^user$/ }) })).toHaveAttribute('title', /用户程序执行时间占比/)
})
